# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Business
    local_business_type: ''
    org_name: ''
    description: 'Product management, brand development, and digital design services catering to X-ennial ADHDers.'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "DRTYBB"
      # Logo filename in `assets/media/` folder
      filename: "logo.gif"
    button:
      enable: true
      text: "HugoBlox Templates"
      url: "https://hugoblox.com/templates/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© 2024 DRTYBB LLC'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
